### PR TITLE
Openloan backend

### PR DESCRIPTION
**Pull request by TBomberman**
Backend work
-validation
-allowance check cases for collateral type
-error handling
-check enough balance
-add decimal places to tokens
-add hot toast
ty @Pochetes or @dam417

### CODE REVIEW

**Review by Pochetes — COMMENTED** [review]
## AddLiquidity component Crashing

In this section here
https://github.com/gammaswap/v1-interface/blob/ea1d91d285edae6e4908b48f5bcf79468f76e164/pages/positions/addliquidity.tsx#L158
The `tokenASelected` or `tokenBSelected` variable seems to be null. Can you check to see if it was when you changed the `Token` type to have a decimals property?

##

**Comment by Pochetes** [comment]
> ## AddLiquidity component Crashing
> In this section here
> 
> https://github.com/gammaswap/v1-interface/blob/ea1d91d285edae6e4908b48f5bcf79468f76e164/pages/positions/addliquidity.tsx#L158
> 
> 
> The `tokenASelected` or `tokenBSelected` variable seems to be null. Can you check to see if it was when you changed the `Token` type to have a decimals property?

Fixed this error already in [this commit](https://github.com/gammaswap/v1-interface/pull/13/commits/2023771607a85da926aa432186624c8d1f1c038b)

**Review by Pochetes — COMMENTED** [review]
## Too many `console.log` statements
Please try to only use console.log when you are testing out the app but remember to remove them before you commit your changes.

## Incorrect Validation
Screen Shot 2022-07-16 at 3 56 07 PM

The confirm btn should not enabled until all 3 have an input. It should be disabled if any one of those values  `=== ""`. Make sure you add the logic for when user selects **Both**

Screen Shot 2022-07-16 at 3 59 01 PM
Make sure you add validation for when one of the inputs is blank.

### **Pointer**
A good way to do all this w/o validation is to have a function that checks all inputs `onChange` and toggles the button from visible to disabled and vice versa. That way, the user doesn't have the chance to confirm the transaction with invalid inputs. View my code in `AddLiquidity` to see how I do it.

**Comment by TBomberman** [comment]
Sorry to break addliquidity. Next time I will check it. Question about "|| tokenProp === 18)". Some of the decimals are 6 like USDC. Is 18 ok?

**Comment by TBomberman** [comment]
Reduced console logs. @Pochetes  ty!

**Review by Pochetes — APPROVED** [review]

**Pull request merged**
