### PR TITLE
Redesign addLiquidity UI

### PR DESCRIPTION
**Pull request by Pochetes**
## Overview
- rebuilt `addLiquidity` UI with new color scheme and layout
- created new tabs to allow user to choose between depositing LP or reserve tokens
- cleaned up UI for the new LP token tab (token pair selector)
- fixed a fast refresh bug that reloaded all components instead of the changed one. This was because `AddLiquidityStyles.tsx` was in a non-react folder so I put it back in `AddLiquidity` component.

## Demo
I was stuck on deciding between creating the tabs as tabs or as a switch component. When I created it as a tab component, I realized that it was taking a lot of the space in the entire component. The user would typically click on this once so I don't think we need to have it in the middle.

### This is the tab component version
Screen Shot 2022-09-20 at 11 35 20 PM

### This is the switch component version
Screen Shot 2022-09-21 at 1 53 56 AM

Personally, I think the latter is a better option because we will most likely be adding information/warning boxes inside depending on the user input or any form of metric from the pool. Having the tabs like that will make it too busy.

### This is the content inside the LP token tab
Screen Shot 2022-09-21 at 1 53 45 AM

If you need more reference, Uniswap does the same by having state changing features as a small component like so:
Screen Shot 2022-09-21 at 2 10 36 AM

Thanks!

### CODE REVIEW

**Comment by Pochetes** [comment]
NOTE: Also added TODOs for things we need to finish in future tasks

**Comment by Pochetes** [comment]
Added Max button (for lp token tab too)
Screen Shot 2022-09-21 at 10 10 02 AM

**Review by TBomberman — COMMENTED** [review]
Are we planning to do a separate work for the Approve button? Maybe now I understand why you meant to put the button into a different component. But every page would have to pass the state, validations and actions as delegates props to these button components. 

Uniswap makes the Balance: xxx as the Max button itself. To save space, what do you think of that idea? Also If the balance is big like "Balance: 1.123456" Then the max button will be far out to the left. Just a thought.

Very nice UI.

**Review by TBomberman — APPROVED** [review]

**Comment by Pochetes** [comment]
> But every page would have to pass the state, validations and actions as delegates props to these button components.

Yeah, we can work on this later. As far as the MVP goes, we can just duplicate the code (validation, props, etc.) for now. 

> Uniswap makes the Balance: xxx as the Max button itself. To save space, what do you think of that idea?

I really like the idea. I'll add that into this PR

**Pull request merged**
