### PR TITLE
Swap design work

### PR DESCRIPTION
**Pull request by UsamaSaleem14**
1. Design for swap
2. All mathematical operations are working except for contract integration

Screenshot 2022-08-14 at 13-13-23 GammaSwap
Screenshot 2022-08-14 at 13-13-32 GammaSwap

### CODE REVIEW

**Comment by TBomberman** [comment]
@Pochetes or @dam417 it looks ok to me

**Comment by dam417** [comment]
The button can be called swap but the name of the link to access the view should have a more descriptive name such as "rebalance"

**Review by dam417 — CHANGES_REQUESTED** [review]
Change name of link to the swap view to "rebalance" or a better name if you think there's one. Action button can still be called swap.

**Comment by TBomberman** [comment]
Changed link to rebalance. Also moved the swap context to inside positions, deleting the swap option in the header plus clean up.

**Review by dam417 — APPROVED** [review]

**Pull request merged**
