### PR TITLE
Repay and withdraw design

### PR DESCRIPTION
**Pull request by UsamaSaleem14**

### CODE REVIEW

**Comment by TBomberman** [comment]
image
Can you put sliders as in the screenshot like this:
I put yarn.lock in the gitignore, but not sure why it isn't working. Can you check why its' not being ignored?

**Review by Pochetes — CHANGES_REQUESTED** [review]
@UsamaSaleem14
1. The `WithdrawLiquidity` component should have two buttons: one that approves the action with a signer, and then another that executes the removal once it has been approved. Similar to screenshot below.

Screen Shot 2022-07-01 at 9 20 18 AM

2. Also move the `style.formLabel` div below the input field. We want to emphasize the user's input first and then display information. Try to give it a little bit of separation. 

3. Don't forget to indent children elements. Good code formatting is required.

**Comment by TBomberman** [comment]
For 1. 2 buttons, I was planning to make a 2 button component for all the three screens and then Usama can use it in this component.

**Comment by Pochetes** [comment]
Just keep committing on this branch so that we don't have to open redudant PRs.

**Comment by TBomberman** [comment]
Right, see how it works out.

**Pull request merged**
